version: "3.9"

services:
  auth_postgres:
    container_name: auth-postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=$AUTH_POSTGRES_USER
      - POSTGRES_PASSWORD=$AUTH_POSTGRES_PASSWORD
      - POSTGRES_DB=$AUTH_POSTGRES_DB
    ports:
      - "5433:5432"