name: Docker Build

on:
  pull_request:
    branches: [main, staging]

jobs:
  build-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v44
      - name: Build Docker image if needed
        if: |
          contains(steps.changed.outputs.all_changed_files, 'backend/auth/') ||
          contains(steps.changed.outputs.all_changed_files, 'backend/auth/Dockerfile')
        run: docker build -f backend/auth/Dockerfile -t flashrust-auth:pr-${{ github.event.pull_request.number }} .
