name: Tests
on:
  pull_request:
    branches: [ "main" ]
jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run unit tests in backend folder
        working-directory: ./backend
        run: cargo test --locked --features=unit
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.AUTH_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.AUTH_POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.AUTH_POSTGRES_DB }}
    env:
      AUTH_DATABASE_URL: postgres://${{ secrets.AUTH_POSTGRES_USER }}:${{ secrets.AUTH_POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.AUTH_POSTGRES_DB }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run integration tests in backend folder
        working-directory: ./backend
        run: cargo test --locked --features=integration
